### ISSUE TITLE
Robot visualizer

### ISSUE THREAD

**Issue by niharmitra** [team8/robot-dashboard#7]
Ability to visualize either the robot as a whole or parts of it based on sensor input perhaps.
Ex: Tyr shooter to show the latch lock status more clearly, or if we had a robot that could say, accumulate from various sides, with A being the button press for one side and B being the button press for the other side, it would show a rotating simplified display of the robot so it's easy to know which side is facing which, etc.

**Comment by JonathanZwiebel** [comment]
What is the difference between this and #4 ?

**Comment by rselwyn** [comment]
Closing for the reason mentioned above.
