### ISSUE TITLE
Create a Display for Match Information from the DriverStation Object

### ISSUE THREAD

**Issue by JonathanZwiebel** [team8/robot-dashboard#8]
Add a display into the match view that includes match time, game period (auto, tele, disabled), battery voltage, and brownout state. These items should call visual attention when changing states (ex. match time running close to zero, brownout or near-brownout approaching) and should be easily visible to the drive coach.

**Comment by rselwyn** [comment]
I was also thinking that we could implement something that monitors the number of match brownouts and if too many are sensed, a battery warning will show for the rest of the match.  Do you think this is a good idea or is useful @JonathanZwiebel ?

**Comment by bdavies01** [comment]
Ready for testing

**Comment by rselwyn** [comment]
This code has been tested and is working.

**Comment by rselwyn** [comment]
#20 closes this.
